/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.*;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Benjy
 */
public class MainGameUI extends javax.swing.JFrame {

    GameLogic gameLogic;
    /**
     * Creates new form MainGameUI
     */

    JButton[] Buttons = new JButton[20];
    char guessed;
    int totalAttempts = 5, gameLevel = 0, gameMode = 0, noOfWords=0,wins=0;
    
    public MainGameUI(int gameMode, int gameLevel) {
        this.gameLevel = gameLevel;
        this.gameMode = gameMode;
        initComponents();
        gameLogic = new GameLogic(this);
        mainTxt.setText("Guess the word by typing the Letter - you are playing "+gameMode+" word guess mode ");
        initialize();
        setLocationRelativeTo(null);
    }

    private void initialize() {
        wordPanel.setLayout(new GridLayout(1, 20));
        gameLogic.readWords();
        noOfWords = noOfWords+1;
        totalAttempts = 5;
        guessTxt.requestFocus();
        attemptsTxt.setText("You have " + totalAttempts + " attempts in total");
        guessedTxt.setText("status of guessed");
        gameLogic.RandomWord();
        //System.out.println(this.gameLevel);
        gameLogic.maskString(gameLogic.currentWord, gameLevel);
        updateButtons(gameLogic.maskedWord);
    }

    private void updateButtons(String str) {
        wordPanel.removeAll();
        wordPanel.setLayout(new GridLayout(1, 20));
        for (int i = 1; i <= str.length(); i++) {

            Buttons[i] = new JButton();
            Buttons[i].setVisible(true);
            Buttons[i].setPreferredSize(new Dimension(45, 45));

            Buttons[i].setText(gameLogic.maskedWord.charAt(i - 1) + "");
            wordPanel.add(Buttons[i]);
            wordPanel.revalidate();
            wordPanel.repaint();
            //wordPanel.add(Box.createHorizontalStrut(20));

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        revealBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        giveUpBtn = new javax.swing.JButton();
        attemptsTxt = new javax.swing.JTextField();
        guessedTxt = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        mainTxt = new javax.swing.JTextField();
        wordPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        guessTxt = new javax.swing.JTextField();
        cheatLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        revealBtn.setFont(new java.awt.Font("Serif", 1, 13)); // NOI18N
        revealBtn.setText("Reveal");
        revealBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revealBtnActionPerformed(evt);
            }
        });

        clearBtn.setFont(new java.awt.Font("Serif", 1, 13)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        giveUpBtn.setFont(new java.awt.Font("Serif", 1, 13)); // NOI18N
        giveUpBtn.setText("I give up on this word!");
        giveUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giveUpBtnActionPerformed(evt);
            }
        });

        attemptsTxt.setEditable(false);
        attemptsTxt.setBackground(new java.awt.Color(51, 51, 255));
        attemptsTxt.setFont(new java.awt.Font("Serif", 1, 13)); // NOI18N
        attemptsTxt.setForeground(new java.awt.Color(255, 255, 255));
        attemptsTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        attemptsTxt.setText("You have 5 Attempts left");

        guessedTxt.setEditable(false);
        guessedTxt.setBackground(new java.awt.Color(51, 51, 255));
        guessedTxt.setFont(new java.awt.Font("Serif", 1, 13)); // NOI18N
        guessedTxt.setForeground(new java.awt.Color(255, 255, 255));
        guessedTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        guessedTxt.setText("status of guessed");

        backBtn.setFont(new java.awt.Font("Serif", 1, 13)); // NOI18N
        backBtn.setText("Go back to main Menu");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        mainTxt.setEditable(false);
        mainTxt.setBackground(new java.awt.Color(51, 51, 255));
        mainTxt.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        mainTxt.setForeground(new java.awt.Color(255, 255, 255));
        mainTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mainTxt.setName(""); // NOI18N

        javax.swing.GroupLayout wordPanelLayout = new javax.swing.GroupLayout(wordPanel);
        wordPanel.setLayout(wordPanelLayout);
        wordPanelLayout.setHorizontalGroup(
            wordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        wordPanelLayout.setVerticalGroup(
            wordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Enter a Letter please:  ");

        guessTxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        guessTxt.setToolTipText("Enter guessed Letter");
        guessTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                guessTxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                guessTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTxt, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(guessedTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guessTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(revealBtn)
                                .addGap(18, 18, 18)
                                .addComponent(clearBtn))
                            .addComponent(giveUpBtn))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(attemptsTxt)
                            .addComponent(backBtn)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(cheatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(wordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(mainTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(revealBtn)
                                .addComponent(clearBtn)
                                .addComponent(guessTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(giveUpBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cheatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guessedTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(attemptsTxt)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guessTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guessTxtKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c == '#'){
            cheatLabel.setText("Hint: "+gameLogic.currentWord);
        }
        if (Character.isLetter(c) || Character.isISOControl(c)) {
            guessTxt.setEditable(true);
            cheatLabel.setText(null);
        } else {
            guessTxt.setEditable(false);
        }

    }//GEN-LAST:event_guessTxtKeyPressed

    private void guessTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guessTxtKeyTyped
        // TODO add your handling code here:
        if (guessTxt.getText().length() >= 1) { // limit to 3 characters
            evt.consume();
        }
    }//GEN-LAST:event_guessTxtKeyTyped

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        guessTxt.setText("");
        guessTxt.requestFocus();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void revealBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revealBtnActionPerformed
        // TODO add your handling code here:
        int noOfTrys = 0;
        
        try {
            guessed = guessTxt.getText().charAt(0);
            guessTxt.requestFocus();
            //System.out.println(guessed);
            char[] ch = gameLogic.currentWord.toCharArray();
            char[] ch2 = gameLogic.maskedWord.toCharArray();
            guessTxt.setText("");
            guessTxt.requestFocus();
            for (int i = 0; i < ch.length; i++) {
                if (ch[i] == guessed) {
                    ch2[i] = guessed;
                    guessedTxt.setText(""+guessed + " is found successfully");
                    gameLogic.maskedWord = new String(ch2);
                    updateButtons(gameLogic.maskedWord);
                } else  {
                    noOfTrys = noOfTrys + 1;
                }
            }//for loop
            if (noOfTrys == ch2.length) {
                guessedTxt.setText(""+guessed + " is a wrong guess");
                totalAttempts--;
                //System.out.println(totalAttempts);
                if(totalAttempts == 0){
                    JOptionPane.showMessageDialog(this, "You Ran out of Attempts try again!!!");
                    initialize();
                }
                //System.out.println(gameLogic.currentWord);
                attemptsTxt.setText("You have " + totalAttempts + " attempts left");
            }
            if(gameLogic.maskedWord.equals(gameLogic.currentWord)){
                    JOptionPane.showMessageDialog(this, "Correct Guess!!!");
                    wins = wins+1;
                    
                    if(noOfWords == gameMode){
                        if((gameMode == 4)&&(wins>=2)){
                            JOptionPane.showMessageDialog(this, "You Won this Section");
                        }
                        else if((gameMode == 6)&&(wins>=3)){
                            JOptionPane.showMessageDialog(this, "You Won this Section");
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "You Lost this Section");
                        }
                    }
                    initialize();
                }
            
            //System.out.println(gameLogic.maskedWord);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter a letter!!");
            guessTxt.requestFocus();
        }
    }//GEN-LAST:event_revealBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        int confirmation = JOptionPane.showConfirmDialog(this, "Are you sure you want to continue with this choice?");
        if (confirmation == 0) {
            dispose();
            HomeUI home = new HomeUI();
            home.setVisible(true);
        }
        guessTxt.requestFocus();
    }//GEN-LAST:event_backBtnActionPerformed

    private void giveUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giveUpBtnActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(this, "Are you sure you want to continue with this choice?");
         if(input == 0){
             initialize();
         }
         else
             guessTxt.requestFocus();
    }//GEN-LAST:event_giveUpBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainGameUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField attemptsTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel cheatLabel;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton giveUpBtn;
    private javax.swing.JTextField guessTxt;
    private javax.swing.JTextField guessedTxt;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mainTxt;
    private javax.swing.JButton revealBtn;
    private javax.swing.JPanel wordPanel;
    // End of variables declaration//GEN-END:variables
}
